export default [
    'v-hover',
    'v-icon',
    'v-card',
    'v-row',
    'v-fade-transition',
    'v-container',
    'v-img',
    'v-app-bar',
    'v-spacer',
    'v-tooltip',
    'v-card-title',
    'v-card-text',
    'v-divider',
    'v-expand-transition',
    'v-list',
    'v-card-actions',
    'v-btn'
]
